runtime: java11

env: standard

env_variables:
  APPLICATION_SECRET: B5FvQWnTp718vr6RHyvdGlrHBGXcvuM4y4jUeRCaXxIwBZIxt

handlers:
  - url: /.*
    script: this.served
    secure: always
    redirect_http_response_code: 301
